import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>my-cv</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.headerContainer}>
        <div className={styles.header}>
          <p className={styles.home}>Home</p>
          <p>About</p>
        </div>
      </header>

      <main>
        <section className={styles.mainContainer}>
          {/* first section */}
          <div className={styles.headerProfile}>
            <Image
              height={190}
              width={190}
              className={styles.image}
              src="/me.jpg"
              alt="me"
            />
            <div className={styles.personal}>
              <h1>IBRAHIM EKA PUTRA NURLETTE</h1>
              <h3>FRONTEND DEVELOPER</h3>
            </div>
          </div>

          {/* second section */}
          <div className={styles.summarySection}>
            <div className={styles.firstSection}>
              <h4>SUMMARY</h4>
              <p className={styles.summaryDescription}>
                I am a Frontend Developer, my expertise is to create websites
                using React js and mobile applications using React Native. I
                want to continue to learn and improve my skills so that I can
                create interesting applications.
              </p>
            </div>

            <div className={styles.secondSection}>
              <h4>MY SKILL</h4>
              <p>
                - Javascript
                <br /> - React Js
                <br /> - Typescript
                <br /> - Redux
                <br /> - React Native
                <br /> - CSS
                <br /> - Html
                <br /> - Git Github
              </p>
            </div>

            <div className={styles.thirdSection}>
              <h4>
                Frontend Developer in KJMIS
                <br /> Maret-2020 - Now
              </h4>
              <p>
                What i do ?
                <br /> - Build mobile banking app with react native
                <br /> - Create a website to control users in the mobile banking
                application
                <br /> - Build e-commerce app with react native
              </p>
            </div>

            <div className={styles.fourSection}>
              <h4>TRAINING</h4>
              <h4>
                Bootcamp DumbWays.id
                <br />
                Februari-2020 - Maret-2020
              </h4>
              <p>
                What i learn ?
                <br /> - React js to create an application user interface
                <br /> - Express js to process data in the backend application
                <br /> - Redux for state management
                <br /> - Learn basic react native for mobile applications
                <br /> - Learn soft skill
              </p>
            </div>

            <div className={styles.fiveSection}>
              <h4>CONTACT</h4>
              <p>
                Phone : 082110839417
                <br />
                Email : ibraputra843@gmail.com
                <br />
                Github :{" "}
                <a href="https://github.com/ibranurlette">
                  https://github.com/ibranurlette
                </a>
                <br />
                Linkedin :
                <a href="https://www.linkedin.com/in/ibra-nurlette/">
                  https://www.linkedin.com/in/ibra-nurlette/
                </a>
              </p>
            </div>

            <div className={styles.sixSection}>
              <h4>EDUCATION</h4>
              <strong>Madrasah aliyah negeri ambon</strong>
              <p>Graduates of the Year 2018</p>
              <p>
                - Students from 2016 to 2018
                <br />- Islamic mental treasurer
              </p>
            </div>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Created By Ibra Nurlette
        </a>
      </footer>
    </div>
  );
};

export default Home;
